### ISSUE TITLE
my fullscreen is broken

### ISSUE THREAD

**Issue by LichtUmbra** [NsCrosu/DEMO-inksansGMS2#11]
when i want to open the fullscreen whit f4 or alt+enter this happens

![Sin título](https://user-images.githubusercontent.com/71770558/94016646-c0c70400-fd84-11ea-98f7-4b7ede908bd2.png)

i already reinstalled the game and the bug still here

**Comment by NsCrosu** [comment]
i dont know what happens
maybe u can use another computer
or try f4 in hellmode(?
but i'm sure that's not a coding mistake

**Comment by NsCrosu** [comment]
FIXED
