### ISSUE TITLE
Cant print text after phase2(Xans)

### ISSUE THREAD

**Issue by ChariskRichy** [NsCrosu/DEMO-inksansGMS2#12]
在Xans后，蓝屏，会出现一段话:Please dont come back，但是在手机版本上会报错
![Screenshot_2020-10-03-17-51-54-878_com alteruniverse ink](https://user-images.githubusercontent.com/38654262/95008127-9bd05d80-05dc-11eb-9812-5df39c25e195.jpg)猜测可能是代码GMS的问题qwq

**Comment by NsCrosu** [comment]
确实，我忘了这回事了
等手机版更新小版本再说吧（如果有的话）

**Comment by NsCrosu** [comment]
FIXED
