### ISSUE TITLE
[Bug]全階&Hell Mode的一個漏洞

### ISSUE THREAD

**Issue by MAngel496** [NsCrosu/DEMO-inksansGMS2#14]
![Screenshot_20201006_120620_com huawei himovie](https://user-images.githubusercontent.com/72427846/95157723-79049b80-07cc-11eb-9b55-feee6292b55e.jpg)
我某次在練Hell Mode時發現的一個漏洞...
呃，在這回合的最後幾秒死掉，按左右鍵就會有好多決心同時碎掉...
希望南省能修復這個漏洞ww

**Comment by NsCrosu** [comment]
FIXED
