### ISSUE TITLE
Can I have the source code?

### ISSUE THREAD

**Issue by nthung-2k5** [NsCrosu/DEMO-inksansGMS2#15]
Can I have the source code?
I want to try to port the game to Godot game engine

**Comment by nthung-2k5** [comment]
Please?

**Comment by NsCrosu** [comment]
I am also very interested in godot and I had the idea of porting isf to godot, too
but the thing is, i have no time

Are you good at godot?
maybe you can
As long as you don’t publish what you do

**Comment by nthung-2k5** [comment]
Don't worry.
After I finished porting, I will send the game to you.

**Comment by nthung-2k5** [comment]
Oh, and if you need to send me the source code, here's the email:
hungthitkhia@gmail.com

**Comment by nthung-2k5** [comment]
I mean, i need the original source code of the game, not the one on this github site
So i wonder if you can send me the source code by email

**Comment by NsCrosu** [comment]
off, sorry
i mean, this game is not made all by myself and some of the members in my team seems don't like it sooo much.. :(
btw, if u r not so good @ chinese, you can hardly underst& the code of the game in somewhere
so----

**Comment by nthung-2k5** [comment]
I look through the entire code of this repo and the old version 0.37 and i understand everything
Besides, i’m not going to upload it
Due to the “decompile” law states that decompile is legal “for personal uses”

**Comment by NsCrosu** [comment]
and then i guess u can build the game based on that version..X?

**Comment by NsCrosu** [comment]
and u can also decomplie v0.39(?

**Comment by nthung-2k5** [comment]
v0.39 is made on gms 2.3, can't be decompiled (completely).
and so as the 0.37
that's why i need the source code

**Comment by NsCrosu** [comment]
WON'T PICK
