### ISSUE TITLE
【bug】三阶段打完绿瓶再重进后，绿瓶又回来了

### ISSUE THREAD

**Issue by woshichulaidajiangyoudex** [NsCrosu/DEMO-inksansGMS2#17]
![QQ截图20201226135811](https://user-images.githubusercontent.com/76607767/103146327-789fef00-4782-11eb-8093-265b374fbc03.png)
![QQ截图20201226135921](https://user-images.githubusercontent.com/76607767/103146333-91100980-4782-11eb-9cd9-97baa8d6380d.png)
前一张是打破瓶子的图，后一张是重进后瓶子恢复了的图
（视频压缩后还是太大所以只能截两张图了）

**Comment by NsCrosu** [comment]
FIXED
