### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Eevee-UwU** [NsCrosu/DEMO-inksansGMS2#18]
![Captura de pantalla (4)](https://user-images.githubusercontent.com/77632764/104941896-ad6a2500-5981-11eb-8651-3ef4184600df.png)
why i resolve this problem

**Comment by NsCrosu** [comment]
restart your game, or reboot your computer

It’s gms2 bug, I can’t fix it(

**Comment by Eevee-UwU** [comment]
i try restart all and no

**Comment by NsCrosu** [comment]
try more times, and it may be ok
I had this problem as well before

**Comment by Eevee-UwU** [comment]
no response ;(

**Comment by Eevee-UwU** [comment]
in the pass version i can play it but now no ;(

**Comment by Eevee-UwU** [comment]
i do all and i can't play this wonderful game

**Comment by NsCrosu** [comment]
still can not?

**Comment by NsCrosu** [comment]
strange

**Comment by NsCrosu** [comment]
that”s your system’s problem, maybe you can try to change a computer

**Comment by NsCrosu** [comment]
or try to install some c++ libraries(but they should included in win10, idk)

**Comment by Eevee-UwU** [comment]
i have windows 8.1 pro

**Comment by Eevee-UwU** [comment]
and i don't have money for a new computer

**Comment by NsCrosu** [comment]
you can try to play other games that made with GMS2 ( like OS-T by fdy )and see if this problem occurs again
