### ISSUE TITLE
【bug】二阶段ESPE踏板回合有bug以及onlyfun疑似有无缝攻击以及steam回合日墙的bug以及一阶段重大致命bug

### ISSUE THREAD

**Issue by JPG114514** [NsCrosu/DEMO-inksansGMS2#19]
尊敬的南省Crosu：
你好！
我作为一个isf的忠实玩家，看到您的isf0.39版本发布了，我很高兴，但是随着时间的推移，仅仅在二阶段（当然有很大我菜的成分在里面），我就遇到了不少问题，特此反馈。
ESPE最后踏板回合（无法上传图片，故用文字解释）：当我站在最高踏板上并且回合结束时，战斗框会变扁，此时灵魂会直接从战斗框顶部压下来与火球相撞，造成无法躲避的10点伤害。
onlyfun疑似无缝：当我处于红色灵魂时，密集的橙色三角形会对我造成伤害（并且还有龙骨炮），这里疑似有伪无缝。以及锁链锁住我的时候，onlyfun会再召唤一个自己，这个橙色三角形也会对我造成伤害，并且由于我无法移动导致无法躲避，造成10点伤害。
steam回合bug：大风车过后有一个橙蓝激光的回合，如果我站在中间的平台持续按↓键，不论是哪种激光都不会对我造成伤害。
一阶段重大致命bug：心灵结晶回合结束后有极大几率直接弹出错误代码，退出重进还是一阶段，只有极小几率出现六骨回合进入二阶段。我身边有几个朋友也是这样。
特此反馈。
       此致
敬礼
又：正值新春佳节，祝南省新年快乐！
                                                                                                                                                                                  2020.2.11

**Comment by NsCrosu** [comment]
感谢你的报告以及这封可爱的信！由于我的学业繁忙所以才抽出时间回复，还请见谅！

在此我一一对其中的各项进行说明。
上传图片可以用 sm.ms 这个网站，然后po上图片地址。
ESPE回合可以通过在回合结束前不跳上最后一个板子，在倒数第二个板子边缘放置灵魂来躲避，已有相关无伤视频存在。
OnlyFunny回合的所有橙色三角形都为【橙色攻击】，需要按住方向键躲避。
顺便，OnlyFunny回合将会在下一次版本更新中大更改（如果有下一版本的话）
Steam回合中的橙蓝判定bug个人认为没有很大影响。
心灵结晶回合结束后的报错可以通过一阶段内不使用任何Item或者按下G键解决。原理是消除数组超界对心灵结晶回合结束后的Item列表修改的影响。对于不使用Item依然报错的情况，则可以通过不过量使用（即多次选择直到该选项消失）Act内的除Check外的选项解决。

最后—— 感谢你的反馈！这款游戏会因为你的反馈而变的更好！
