### ISSUE TITLE
Bug Phase 2 :jump platform

### ISSUE THREAD

**Issue by Diax45** [NsCrosu/DEMO-inksansGMS2#2]
This phase 2 he can be adjust because when you jump on a platform , the soul is falling many times on the platform and you can't jump correctly  , you can adjuts this please ? 

This game is the best fangame ^^

**Comment by KaYZaI** [comment]
Yay I have the same bug on the moving platform (on the duo after Ultra sans)

**Comment by NsCrosu** [comment]
will fix

**Comment by NsCrosu** [comment]
FIXED

**Comment by MrAmaze99** [comment]
I still have the issue to this day tho
