### ISSUE TITLE
[BUG]游戏中板子手感很糟糕

### ISSUE THREAD

**Issue by LICKIL** [NsCrosu/DEMO-inksansGMS2#20]
第二阶段的第二个回合和骷髅大队长后面的回合由于**板子的糟糕手感**，而且**碰撞箱**和**贴图**位置**错位**，还会**弹跳**？！使其游玩很糟糕，在**0.37时候没有**，也许迁移至GM2时产生的吧，希望尽快优化 。

视频[由于超过限制<_<,只好发蓝凑云(lll￢ω￢)，可以谅解吧....qwq]
https://wwe.lanzous.com/i1Inoln1xve

**Comment by NsCrosu** [comment]
FIXED
