### ISSUE TITLE
Keeps crashing

### ISSUE THREAD

**Issue by kietay222** [NsCrosu/DEMO-inksansGMS2#27]
The Ink sans fight crashed right after the 7 soul sans attack finished, is this a bug or is there a way to fix it?

**Comment by NsCrosu** [comment]
I’m sorry for the bad game experience, and this is a known issue.
The reason is that the game tried to set values to non-existing items since you have used some items.
One of the solutions is to press G before the 7 soul sans, and don’t use any item. The game should refill the item list.

**Comment by kietay222** [comment]
> I’m sorry for the bad game experience, and this is a known issue. The reason is that the game tried to set values to non-existing items since you have used some items. One of the solutions is to press G before the 7 soul sans, and don’t use any item. The game should refill the item list.

Okay thanks man ill make sure to try it, ur game is rly good btw :)
