### ISSUE TITLE
【Bug】 第一階段 murder sans， 他把我甩出戰鬥框了

### ISSUE THREAD

**Issue by MilkTEA812** [NsCrosu/DEMO-inksansGMS2#3]
![unknown (1)](https://user-images.githubusercontent.com/70576372/91837943-50dec580-ec7f-11ea-9872-680df4669970.png)

**Comment by NsCrosu** [comment]
version v0.39 ?
i only know this bug in v0.41beta(old)

**Comment by MilkTEA812** [comment]
yes， it  is  v0.39 , i download on gamejolt ;w; 回合一開始他甩我去左邊 而我一直按著向左的方向 然後就丟了出去 可能是卡bug了 之後玩就沒發生 或者是有幾率出現的bug吧 ？？？

**Comment by NsCrosu** [comment]
好吧，這很古怪，但我暫且先記下來了，以後會修復的 ;w;

**Comment by NsCrosu** [comment]
FIXED
