### ISSUE TITLE
【Code Error】沒看懂 ;w;???

### ISSUE THREAD

**Issue by MilkTEA812** [NsCrosu/DEMO-inksansGMS2#4]
![unknown (2)](https://user-images.githubusercontent.com/70576372/91959595-65809380-ed3b-11ea-8e13-83a6053424a8.png)

**Comment by NsCrosu** [comment]
will fix
plz use ACT less ;w;

**Comment by MilkTEA812** [comment]
okok ;w;  I wont flirt Ink anymore ;w; :(

**Comment by NsCrosu** [comment]
press G may help you 
and, 

FIXED
