### ISSUE TITLE
【bug】第一阶段蓝莓和fell的对话弄反了

### ISSUE THREAD

**Issue by HelloWRC** [NsCrosu/DEMO-inksansGMS2#6]
以下是0.39错误区域视频：
[Uploading 2020-09-06 11-48-38 [低质量和大小].zip…]()

**Comment by NsCrosu** [comment]
你的zip是不是没上传完就comment了，我看到的只有 Uploading 的链接

**Comment by HelloWRC** [comment]
应该是，我重新传一下
[2020-09-06 11-48-38 [低质量和大小].zip](https://github.com/NsCrosu/DEMO-inksansGMS2/files/5179063/2020-09-06.11-48-38.zip)

**Comment by NsCrosu** [comment]
我局的没啥不对

**Comment by HelloWRC** [comment]
蓝莓那里不应该是Just you and him吗(0.37)

**Comment by HelloWRC** [comment]
然后在0.39变成You have to end this了

**Comment by NsCrosu** [comment]
FIXED
