### ISSUE TITLE
【bug】物品栏切换战斗时按TAB会文字重叠

### ISSUE THREAD

**Issue by Wulian233** [NsCrosu/DEMO-inksansGMS2#8]
我发现了ink sans0.39的一个bug，就是在对战中或者物品栏切换对战中的一瞬间按Tab切换音乐，它会把you got lost写在原本的物品栏的对话框中，直到下一次的物品栏再按Tab他才会消失！

本人联系方式，bilibili捂脸祖 您可以观看视频的完整版，qq1055917385
[瑙嗛[1].zip](https://github.com/NsCrosu/DEMO-inksansGMS2/files/5213977/1.zip)
谢谢！

**Comment by NsCrosu** [comment]
FIXED
